version: 2

sources:
  - name: public
    tables:
      - name: vnt

models:
  - name: flatten_vnt
    config:
      schema: public
    #columns:
    #  - name: id
    #    tests:
    #      - unique
    #      - not_null
